"use client";

import { useState, useEffect } from "react";
import {
  Sparkles,
  Type,
  MousePointerClick,
  BarChart3,
  Table2,
  GitCommit,
  Image as ImageIcon,
  CheckCircle2,
  X,
  ChevronRight,
  ChevronLeft,
  HelpCircle,
  Pencil,
  Move,
  Layers,
  Palette,
  Wand2,
} from "lucide-react";
import { Button } from "@/components/ui";
import { useUser } from "@clerk/nextjs";
import { markTutorialSeen, TUTORIAL_FLAGS } from "@/lib/auth/tutorial";

interface ElementTutorialModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const STEPS = [
  {
    id: "welcome",
    title: "Welcome to Lumina Slide Editor",
    subtitle: "Learn how to interact with and edit every element in your presentation",
    icon: Sparkles,
    color: "from-indigo-500 to-purple-600",
    highlights: [
      "Every element generated by AI is 100% editable and customizable",
      "Click elements to select, move, resize, rotate, or re-style",
      "Double-click text boxes for instant inline editing on the slide canvas",
    ],
    demo: {
      type: "text",
      sample: "Double-click me on the slide to edit!",
    },
  },
  {
    id: "text",
    title: "1. Headings & Text Boxes",
    subtitle: "Inline editing on the slide canvas + floating text formatting bar",
    icon: Type,
    color: "from-blue-500 to-cyan-500",
    highlights: [
      "Double-Click: Opens a live text editor directly on top of the slide",
      "Floating Toolbar: Adjust font size, font family, bold, italic, text color, and alignment",
      "Inspector Panel: AI Rewrite button rewrites text to be punchy, executive, or concise",
    ],
    tips: "Pro Tip: Highlight text and press Ctrl+Enter (or Cmd+Enter) to save changes quickly.",
  },
  {
    id: "canvas",
    title: "2. Move, Resize & Rotate",
    subtitle: "Fluid 8-point grid positioning and snapping",
    icon: Move,
    color: "from-emerald-500 to-teal-600",
    highlights: [
      "Move: Click and drag any element anywhere on the slide",
      "Resize: Drag any of the 8 blue corner handles to scale width and height",
      "Rotate: Drag the top rotation handle to spin elements at any angle",
      "Grid Snap: Click the grid icon (⧉) in the bottom zoom bar for 8px precision alignment",
    ],
    tips: "Pro Tip: Select elements and use Arrow keys for 1px adjustments, or Shift+Arrow for 10px moves.",
  },
  {
    id: "charts_tables",
    title: "3. Charts, Tables & Data Visuals",
    subtitle: "Interactive data updates via the right Inspector panel",
    icon: BarChart3,
    color: "from-amber-500 to-orange-600",
    highlights: [
      "Select Chart: Click any Bar, Line, Pie, or Donut chart to view data settings",
      "Edit Data: Update labels and numerical values in the right Inspector tab",
      "Tables: Edit table headers and row cells, or adjust column counts dynamically",
    ],
    tips: "Pro Tip: Enter chart data in format 'Label: Value' line by line in the Inspector text area.",
  },
  {
    id: "diagrams",
    title: "4. Timelines, Flowcharts & Architecture",
    subtitle: "Node-based diagram and roadmap editing",
    icon: GitCommit,
    color: "from-fuchsia-500 to-pink-600",
    highlights: [
      "Select Diagram: Click any timeline, mindmap, flowchart, or architecture visual",
      "Update Nodes: Change step labels line by line in the Inspector panel",
      "Dynamic Layout: Lumina automatically recalculates spacing and node connections",
    ],
    tips: "Pro Tip: Use AI Copilot on the right sidebar to generate brand new custom diagrams instantly.",
  },
  {
    id: "backgrounds",
    title: "5. Backgrounds & AI Visuals",
    subtitle: "Background library browser + 4-candidate FLUX AI background generator",
    icon: Palette,
    color: "from-violet-500 to-indigo-600",
    highlights: [
      "Background Library: Select Solid colors, Gradients, Mesh, Glassmorphism, or Animated effects",
      "4-Option AI Generator: Prompt FLUX 1.0 to generate 4 HD candidate background images",
      "1-Click Apply: Apply your chosen background to the current slide or the entire deck",
    ],
    tips: "Pro Tip: Open the Asset Library tab to browse curated background presets.",
  },
  {
    id: "copilot",
    title: "6. AI Copilot Assistant",
    subtitle: "Full-deck QA auto-repair, graphic insertion, and content rewriting",
    icon: Wand2,
    color: "from-rose-500 to-red-600",
    highlights: [
      "Design Auto-Repair: Audits contrast, hierarchy, density, and layout variety",
      "AI Graphics: Generate Stable Diffusion XL graphics and insert directly onto slides",
      "Deck QA: 1-click optimization to ensure design review scores above 95%",
    ],
    tips: "You're all set! Click 'Start Editing' to begin crafting your presentation.",
  },
];

export function ElementTutorialModal({ isOpen, onClose }: ElementTutorialModalProps) {
  const { user } = useUser();
  const [currentStep, setCurrentStep] = useState(0);

  if (!isOpen) return null;

  const step = STEPS[currentStep];
  const Icon = step.icon;
  const isLast = currentStep === STEPS.length - 1;

  const handleNext = () => {
    if (isLast) {
      markTutorialSeen(user, TUTORIAL_FLAGS.element);
      onClose();
    } else {
      setCurrentStep((s) => s + 1);
    }
  };

  const handlePrev = () => {
    setCurrentStep((s) => Math.max(0, s - 1));
  };

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-md animate-fade-in">
      <div className="relative w-full max-w-2xl overflow-hidden rounded-2xl border border-white/10 bg-slate-900 shadow-2xl">
        {/* Header Gradient */}
        <div className={`relative flex items-center justify-between bg-gradient-to-r ${step.color} p-6 text-white`}>
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-white/20 backdrop-blur-md">
              <Icon size={24} />
            </div>
            <div>
              <span className="text-xs font-semibold uppercase tracking-wider text-white/80">
                Step {currentStep + 1} of {STEPS.length}
              </span>
              <h2 className="text-xl font-bold">{step.title}</h2>
            </div>
          </div>
          <button
            onClick={onClose}
            className="cursor-pointer rounded-lg bg-black/20 p-2 text-white/80 transition-colors hover:bg-black/40 hover:text-white"
          >
            <X size={18} />
          </button>
        </div>

        {/* Content Body */}
        <div className="space-y-6 p-6">
          <p className="text-sm font-medium text-slate-300">{step.subtitle}</p>

          <div className="space-y-3 rounded-xl border border-white/5 bg-slate-950/60 p-4">
            {step.highlights.map((h, i) => (
              <div key={i} className="flex items-start gap-2.5 text-xs text-slate-200">
                <CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-400" />
                <span>{h}</span>
              </div>
            ))}
          </div>

          {step.tips && (
            <div className="rounded-xl border border-indigo-500/20 bg-indigo-500/10 p-3 text-xs text-indigo-200">
              {step.tips}
            </div>
          )}

          {/* Step Selector Dots */}
          <div className="flex items-center justify-center gap-1.5 pt-2">
            {STEPS.map((s, idx) => (
              <button
                key={s.id}
                onClick={() => setCurrentStep(idx)}
                className={`h-2 rounded-full transition-all cursor-pointer ${
                  idx === currentStep ? "w-6 bg-indigo-500" : "w-2 bg-slate-700 hover:bg-slate-500"
                }`}
                title={s.title}
              />
            ))}
          </div>
        </div>

        {/* Footer Controls */}
        <div className="flex items-center justify-between border-t border-white/10 bg-slate-950/40 px-6 py-4">
          <button
            onClick={handlePrev}
            disabled={currentStep === 0}
            className={`flex items-center gap-1 text-xs font-medium cursor-pointer transition-colors ${
              currentStep === 0 ? "opacity-30 cursor-not-allowed text-slate-500" : "text-slate-300 hover:text-white"
            }`}
          >
            <ChevronLeft size={16} />
            Previous
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="cursor-pointer rounded-lg px-3 py-1.5 text-xs font-medium text-slate-400 hover:bg-white/5 hover:text-slate-200"
            >
              Skip Tour
            </button>
            <Button onClick={handleNext} className="gap-1.5">
              <span>{isLast ? "Start Editing" : "Next Step"}</span>
              <ChevronRight size={16} />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
