export type ExportFormat =
  | "markdown"
  | "html"
  | "docx"
  | "pdf"
  | "json"
  | "latex"
  | "notion"
  | "obsidian"
  | "pptx-notes"
  | "clipboard";

export class ExportEngine {
  public static exportDocument(content: string, format: ExportFormat, title: string = "AI_Content_Document"): void {
    if (typeof window === "undefined") return;

    let blob: Blob;
    let filename = `${title.toLowerCase().replace(/\s+/g, "_")}`;

    switch (format) {
      case "markdown":
      case "obsidian":
      case "notion":
        blob = new Blob([content], { type: "text/markdown;charset=utf-8;" });
        filename += ".md";
        break;

      case "html":
        const htmlContent = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>${title}</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1e293b; background: #f8fafc; }
h1, h2, h3 { color: #0f172a; margin-top: 1.5em; }
blockquote { border-left: 4px solid #6366f1; margin: 0; padding-left: 1em; color: #475569; background: #f1f5f9; padding: 10px; border-radius: 4px; }
table { width: 100%; border-collapse: collapse; margin: 20px 0; }
th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
th { background: #e2e8f0; }
code { background: #e2e8f0; padding: 2px 6px; border-radius: 4px; font-family: monospace; }
</style>
</head>
<body>
${markdownToSimpleHTML(content)}
</body>
</html>`;
        blob = new Blob([htmlContent], { type: "text/html;charset=utf-8;" });
        filename += ".html";
        break;

      case "latex":
        const latexContent = `% Generated by Enterprise AI Content Operating System
\\documentclass{article}
\\usepackage[utf8]{utf8}
\\usepackage{hyperref}
\\title{${title}}
\\author{Enterprise AI Engine}
\\date{\\today}

\\begin{document}
\\maketitle

${content.replace(/#/g, "\\section*").replace(/>/g, "%")}
\\end{document}`;
        blob = new Blob([latexContent], { type: "text/x-latex;charset=utf-8;" });
        filename += ".tex";
        break;

      case "json":
        const jsonContent = JSON.stringify(
          {
            title,
            exportedAt: new Date().toISOString(),
            content,
            generator: "Enterprise AI Content OS (DeepSeek + LLaMA)",
          },
          null,
          2
        );
        blob = new Blob([jsonContent], { type: "application/json;charset=utf-8;" });
        filename += ".json";
        break;

      case "docx":
      case "pdf":
      case "pptx-notes":
        // Produce rich formatted text representation
        blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
        filename += `.${format === "docx" ? "docx" : format === "pdf" ? "pdf" : "txt"}`;
        break;

      case "clipboard":
        navigator.clipboard.writeText(content);
        return;
    }

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

function markdownToSimpleHTML(md: string): string {
  return md
    .replace(/^# (.*$)/gim, "h1>$1</h1>")
    .replace(/^## (.*$)/gim, "<h2>$1</h2>")
    .replace(/^### (.*$)/gim, "<h3>$1</h3>")
    .replace(/^> (.*$)/gim, "blockquote>$1</blockquote>")
    .replace(/\*\*(.*)\*\*/gim, "<b>$1</b>")
    .replace(/\*(.*)\*/gim, "<i>$1</i>")
    .replace(/\n/g, "<br/>");
}
